# Generated by Django 6.0.3 on 2026-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255)),
                ('nombre_usuario', models.CharField(max_length=40, null=True, unique=True, verbose_name='Usuario para Login')),
                ('contraseña', models.CharField(max_length=40, null=True)),
                ('estatus_usuario', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=2)),
            ],
            options={
                'verbose_name': 'Usuario de Venta',
                'verbose_name_plural': 'Usuarios de Venta',
            },
        ),
    ]
