# Generated by Django 6.0.3 on 2026-06-16 22:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appValgo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraccionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del fraccionamiento. Ej: 'Toscana', 'Almeras'", max_length=100)),
                ('cuota_mantenimiento', models.DecimalField(decimal_places=2, help_text='Cuota mensual de mantenimiento que paga cada cliente. En Toscana todos pagan $1,070. En Almeras varía por m², pero se configura al crear al cliente.', max_digits=8)),
                ('penalizacion', models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Monto fijo que se suma a la cuota cuando el cliente no paga antes del día límite. Por defecto $200.', max_digits=8)),
                ('dia_limite_pago', models.PositiveSmallIntegerField(default=10, help_text='Día del mes hasta el cual el cliente puede pagar sin penalización. Si hoy es día 11 o después y no ha pagado, se aplica la penalización. Por defecto es el día 10.')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre completo del propietario. Ej: 'OMAR ALVAREZ SOLIS'", max_length=150)),
                ('numero_lote', models.CharField(help_text="Número de lote dentro de la manzana. Ej: '1', '13 Y 14'", max_length=20)),
                ('fraccionamiento', models.ForeignKey(help_text='Fraccionamiento al que pertenece este cliente.', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='appValgo.fraccionamiento')),
            ],
        ),
    ]
