# Generated by Django 6.0.3 on 2026-06-16 22:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appValgo', '0002_fraccionamiento_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el cliente está activo. Un cliente inactivo no genera cuotas nuevas cada mes. Útil para casas que aún no han sido entregadas o propietarios que se fueron.'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='andar',
            field=models.CharField(blank=True, help_text="Nombre del andar dentro del fraccionamiento (aplica en Almeras). Ej: 'DE LA PIEDRA', 'DEL ARBOL', 'DE LAS HOJAS'. Puede quedar vacío si el fraccionamiento no maneja andares.", max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico del propietario. Opcional. Útil para enviar estados de cuenta.', max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_entrega',
            field=models.DateField(blank=True, help_text="Fecha en que se entregó la casa al propietario. A partir de esta fecha el cliente empieza a generar cuotas. Corresponde a la columna 'FECHA DE ENTREGA' de tu Excel.", null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='manzana',
            field=models.CharField(blank=True, help_text="Número o identificador de manzana. Ej: '1', '2'. Puede quedar vacío.", max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referencia',
            field=models.CharField(blank=True, help_text="Clave única de este cliente para identificar sus pagos bancarios. Se genera automáticamente. Ejemplo: 'FRACC1-0042'. El cliente usará esta referencia al hacer su SPEI o depósito.", max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto del propietario. Opcional.', max_length=20),
        ),
        migrations.CreateModel(
            name='CuotaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(help_text='Mes al que corresponde esta cuota. Número del 1 al 12.')),
                ('anio', models.PositiveSmallIntegerField(help_text='Año al que corresponde esta cuota. Ejemplo: 2025.')),
                ('monto_base', models.DecimalField(decimal_places=2, help_text='Monto de la cuota antes de penalización. Se copia del fraccionamiento al generar la cuota, así si la cuota sube el próximo mes, los registros anteriores no cambian.', max_digits=8)),
                ('penalizacion_aplicada', models.BooleanField(default=False, help_text='Indica si ya se aplicó la penalización por atraso. Evita aplicarla dos veces al mismo mes.')),
                ('penalizacion_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de la penalización aplicada. Normalmente $200, pero se guarda aquí por si cambia en el futuro. Es $0.00 si el cliente pagó a tiempo.', max_digits=8)),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha en que el banco confirmó el pago. Vacío si aún no ha pagado.', null=True)),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, help_text='Monto exacto que depositó el cliente según el banco. Puede diferir ligeramente del monto_total (redondeos, pagos parciales). Vacío si aún no ha pagado.', max_digits=8, null=True)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', help_text='Estado actual de esta cuota.', max_length=20)),
                ('notas', models.TextField(blank=True, help_text="Campo libre para observaciones manuales. Ej: 'Cliente llamó para avisar que paga el lunes', 'Pago anual adelantado', 'Ver factura adjunta'.")),
                ('cliente', models.ForeignKey(help_text='Cliente al que pertenece esta cuota.', on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='appValgo.cliente')),
            ],
            options={
                'ordering': ['-anio', '-mes'],
                'unique_together': {('cliente', 'mes', 'anio')},
            },
        ),
    ]
